version: '3.9'

services:
  stock_app:
    build: ./stocks_products
    command: gunicorn stocks_products.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/stock_app/staticfiles/
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    container_name:
    image: cicd:latest
    restart: unless-stopped
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pythonapp_db"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/stock_app/staticfiles/
    ports:
     - 1337:80
    depends_on:
     - stock_app
  volumes:
    postgres_volume:
    static_volume: